// src/components/features/export/pdf-report-template.tsx
'use client';

import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import { Task } from '@/types/task';
import { ReportConfig, TaskReportData } from '@/types/report';
import { format } from 'date-fns';

// PDF Styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
  },
  subtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
  },
  meta: {
    fontSize: 9,
    color: '#9ca3af',
    marginTop: 8,
  },
  section: {
    marginTop: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 10,
  },
  table: {
    width: '100%',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    padding: 8,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    padding: 8,
  },
  tableCell: {
    flex: 1,
  },
  tableCellHeader: {
    flex: 1,
    fontWeight: 'bold',
    fontSize: 9,
    textTransform: 'uppercase',
    color: '#6b7280',
  },
  summaryCard: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 20,
  },
  summaryItem: {
    flex: 1,
    backgroundColor: '#f9fafb',
    padding: 15,
    borderRadius: 4,
  },
  summaryValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
  },
  summaryLabel: {
    fontSize: 10,
    color: '#6b7280',
    marginTop: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#9ca3af',
  },
});

interface TaskReportDocumentProps {
  config: ReportConfig;
  data: TaskReportData;
}

/**
 * Summary Report Template - Overview with KPIs and task list
 */
export function SummaryReportDocument({ config, data }: TaskReportDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>{config.title}</Text>
          {config.subtitle && <Text style={styles.subtitle}>{config.subtitle}</Text>}
          <Text style={styles.meta}>
            Generated: {format(config.generatedAt, 'MMMM d, yyyy h:mm a')}
            {config.dateRange && (
              ` • Data from ${format(config.dateRange.from, 'MMM d')} to ${format(config.dateRange.to, 'MMM d, yyyy')}`
            )}
          </Text>
        </View>

        {/* Summary Cards */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryValue}>{data.totalTasks}</Text>
            <Text style={styles.summaryLabel}>Total Tasks</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryValue}>{data.completedTasks}</Text>
            <Text style={styles.summaryLabel}>Completed</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={[styles.summaryValue, { color: '#ef4444' }]}>{data.overdueTasks}</Text>
            <Text style={styles.summaryLabel}>Overdue</Text>
          </View>
        </View>

        {/* Task Table */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Task Details</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableCellHeader, { flex: 2 }]}>Task</Text>
              <Text style={styles.tableCellHeader}>Status</Text>
              <Text style={styles.tableCellHeader}>Assignee</Text>
              <Text style={styles.tableCellHeader}>Due Date</Text>
            </View>
            {data.tasks.slice(0, 25).map((task, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={[styles.tableCell, { flex: 2 }]}>{task.name}</Text>
                <Text style={styles.tableCell}>{task.status}</Text>
                <Text style={styles.tableCell}>{task.assignee}</Text>
                <Text style={styles.tableCell}>{task.dueDate}</Text>
              </View>
            ))}
          </View>
          {data.tasks.length > 25 && (
            <Text style={{ marginTop: 10, color: '#6b7280', fontSize: 9 }}>
              ... and {data.tasks.length - 25} more tasks
            </Text>
          )}
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          Page 1 of 1 • Generated by Interactive Dashboard
        </Text>
      </Page>
    </Document>
  );
}

/**
 * Detailed Task Report Template - Full task list with all fields
 */
export function DetailedReportDocument({ config, data }: TaskReportDocumentProps) {
  const tasksPerPage = 20;
  const pageCount = Math.ceil(data.tasks.length / tasksPerPage) || 1;

  return (
    <Document>
      {Array.from({ length: pageCount }, (_, pageIndex) => {
        const pageTasks = data.tasks.slice(
          pageIndex * tasksPerPage,
          (pageIndex + 1) * tasksPerPage
        );

        return (
          <Page key={pageIndex} size="A4" style={styles.page}>
            {pageIndex === 0 && (
              <View style={styles.header}>
                <Text style={styles.title}>{config.title}</Text>
                <Text style={styles.meta}>
                  Generated: {format(config.generatedAt, 'MMMM d, yyyy')}
                </Text>
              </View>
            )}

            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.tableCellHeader, { flex: 0.5 }]}>ID</Text>
                <Text style={[styles.tableCellHeader, { flex: 2 }]}>Task</Text>
                <Text style={styles.tableCellHeader}>Status</Text>
                <Text style={styles.tableCellHeader}>Assignee</Text>
                <Text style={styles.tableCellHeader}>Due</Text>
                <Text style={styles.tableCellHeader}>Created</Text>
              </View>
              {pageTasks.map((task, index) => (
                <View key={index} style={styles.tableRow}>
                  <Text style={[styles.tableCell, { flex: 0.5 }]}>{task.id}</Text>
                  <Text style={[styles.tableCell, { flex: 2 }]}>{task.name}</Text>
                  <Text style={styles.tableCell}>{task.status}</Text>
                  <Text style={styles.tableCell}>{task.assignee}</Text>
                  <Text style={styles.tableCell}>{task.dueDate}</Text>
                  <Text style={styles.tableCell}>{task.createdAt}</Text>
                </View>
              ))}
            </View>

            <Text style={styles.footer}>
              Page {pageIndex + 1} of {pageCount}
            </Text>
          </Page>
        );
      })}
    </Document>
  );
}
